### ISSUE TITLE
website returns 502 Bad Gateway

### ISSUE THREAD

**Issue by drewfish** [mattpardee/nodemanual.org#17]
When I try to go to http://nodemanual.org/latest/ I get the following response:

```
502 Bad Gateway - Response Error, a bad response was received from another proxy server or the destination origin server.
```

**Comment by mattpardee** [comment]
Thx Drew, we're working to get it back online. Sorry about the downtime!

**Comment by meteormatt** [comment]
It has been 1 month since the website is down,

**Comment by guozheng** [comment]
yeah, anyone looking into that? I really liked nodemanual ;(

**Comment by mattpardee** [comment]
Back up

**Comment by drewfish** [comment]
Thanks!
